### ISSUE TITLE
[build 2.1.0.v20161203-1029] crash if using new "Split spaces only" option

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#118]
if using new "Split command" option"Split spaces only" at windows

![image](https://cloud.githubusercontent.com/assets/95811/20880917/362c0408-bada-11e6-804e-0b7bb0970e07.png)

it crashes during execution:

java.lang.ArrayIndexOutOfBoundsException: 8
	at de.anbos.eclipse.easyshell.plugin.misc.Utils.splitSpaces(Utils.java:340)
	at de.anbos.eclipse.easyshell.plugin.actions.ActionDelegate.getCommandResolved(ActionDelegate.java:144)
	at de.anbos.eclipse.easyshell.plugin.actions.ActionDelegate.handleExec(ActionDelegate.java:182)

**Comment by anb0s** [comment]
done
