### ISSUE TITLE
"Unhandled event loop exception" with 36 menu items and quick menu

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#149]
```
eclipse.buildId=unknown
java.version=1.8.0_112
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -application org.eclipse.ui.ide.workbench
Command-line arguments:  -application org.eclipse.ui.ide.workbench -data C:\Users\kenobi\workspace/../runtime-EclipseApplication -dev file:C:/Users/kenobi/workspace/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

org.eclipse.ui
Error
Sun Apr 23 11:50:54 CEST 2017
Unhandled event loop exception
...
Caused by: java.lang.IndexOutOfBoundsException: Index: 36, Size: 36
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at de.anbos.eclipse.easyshell.plugin.commands.ExecuteCommandPopup.<init>(ExecuteCommandPopup.java:58)
	at de.anbos.eclipse.easyshell.plugin.handlers.All.execute(All.java:63)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 47 more


```

**Comment by anb0s** [comment]
done
