### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/cdt/core/model/IIncludeReference

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#183]
see #180
...
See you specified the dependency to `cdt.core` as optional in plugin-manifest. Maybe this is the reason why it is not loaded during installation?

After switching back to 2.1.0 it runs again without problems.
...
Just tried out 2.2.0 and got this exception running Eclipse Version: 2020-09 (4.17.0) on Windows 10x64
(2.1.0 runs with problems):

`
java.lang.NoClassDefFoundError: org/eclipse/cdt/core/model/IIncludeReference
        at de.anbos.eclipse.easyshell.plugin.commands.DefineCommands.createContributionItems(DefineCommands.java:53)
        at org.eclipse.ui.internal.menus.ContributionFactoryGenerator.compute(ContributionFactoryGenerator.java:73)
        at org.eclipse.e4.ui.workbench.renderers.swt.ContributionRecord.mergeFactoryIntoModel(ContributionRecord.java:272)
        at org.eclipse.e4.ui.workbench.renderers.swt.ContributionRecord.mergeIntoModel(ContributionRecord.java:216)
        at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.processAddition(MenuManagerRenderer.java:551)
        at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.generateContributions(MenuManagerRenderer.java:530)
        at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.processContributions(MenuManagerRenderer.java:498)
        at org.eclipse.ui.internal.PopupMenuExtender.addMenuContributions(PopupMenuExtender.java:382)
        at org.eclipse.ui.internal.PopupMenuExtender.menuAboutToShow(PopupMenuExtender.java:355)
        at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:338)
        at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:468)
        at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:463)
        at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:495)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4195)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1042)
        at org.eclipse.swt.widgets.Control.WM_INITMENUPOPUP(Control.java:5156)
        at org.eclipse.swt.widgets.Control.windowProc(Control.java:4788)
        at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
        at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1480)
        at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2142)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:4913)
        at org.eclipse.swt.internal.win32.OS.TrackPopupMenu(Native Method)
        at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:237)
        at org.eclipse.swt.widgets.Display.runPopups(Display.java:4053)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3606)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:153)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.lang.ClassNotFoundException: org.eclipse.cdt.core.model.IIncludeReference cannot be found by de.anbos.eclipse.easyshell.plugin_2.2.0.v20201004-2044
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 50 more
`

**Comment by anb0s** [comment]
@makkimesser do you see it during installation or at runtime?

**Comment by makkimesser** [comment]
The exception is shown after installation when eclipse restarts and then at every new start.

**Comment by anb0s** [comment]
fixed at major

**Comment by makkimesser** [comment]
Do you have a test build, which includes this fix and I can test?

**Comment by anb0s** [comment]
pushed new testing build see #192

**Comment by makkimesser** [comment]
Just tested with Eclipse 4.18 and 4.19 (Package "Eclipse IDE for Enterprise Java and Web Developers") on Windows.
No exception any more.
